version: '3'

services:
   web:
      build: .
      command: python ./api/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/api
        - .:/api/autoGmeet
      ports:
        - "8000:8000"
